# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('frequency', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
