# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20161001_1719'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userip',
            table='user_ip',
        ),
    ]
